### PR TITLE
Encode strings for JSON with binaries

### PR DESCRIPTION
**Pull request by sega-yarkin**
Encoding strings use only binaries instead of xmerl_ucs:from_utf8 (which converts it to list) when convert to JSON, it saves some memory and makes RabbitMQ more stable.
We haven't had any issues on production after updating to this code.

### CODE REVIEW

**Comment by sega-yarkin** [comment]
Discussion in GG https://groups.google.com/forum/?hl=en#!topic/rabbitmq-users/3FA3_bJuPIA

**Comment by michaelklishin** [comment]
@sega-yarkin I assume this can go into `3.6.x`?

**Comment by sega-yarkin** [comment]
@michaelklishin Yes, I tested this even in 3.5.7

**Comment by michaelklishin** [comment]
Can you please also submit this against the `stable` branch then?

**Comment by michaelklishin** [comment]
Can you please also submit this against the `stable` branch then?

**Comment by sega-yarkin** [comment]
@michaelklishin sorry for dummy question, but what did you mean under `stable` branch? what should I do?

**Comment by michaelklishin** [comment]
I now see that this particular repo doesn't have the `stable` branch. Fair enough, there's nothing for you to do then :)

**Comment by essen** [comment]
It looks fine, but perhaps we should just switch to jsx or jiffy directly without having this intermediate step?

**Comment by michaelklishin** [comment]
I think it's fine to use this in 3.6.x.

**Comment by essen** [comment]
I have some errors when trying to run the tests. While on a quick glance it seems that it's just the tests that need updating (they're matching against lists instead of binary), it's possible an issue hides there.

I saw that you are new to Erlang so if it's a problem tell me and I'll update the tests directly. Thanks for the patch btw!

**Comment by sega-yarkin** [comment]
@essen Thanks that you mentioned about tests, I forget about case when `encode` should return raw UTF8 bytes (because STOMP doesn't use this option), but I've written it for compatibility now.

Erlang itself is easy to learn language (I've written several RMQ plug-ins for our environment that work well in production already), but there are many tools around the language which I haven't known yet. Can you tell me how to run the tests? :-) Thanks!

**Comment by essen** [comment]
I'm not sure what's the proper way to do it to be honest. I had to do a little trick to make it work with the included rebar. Assuming a clean repo, in the modified file there's an `-ifdef(TEST)` line that I removed, and then also an `-endif` at the end also removed. From there, the command `./rebar get-deps eunit` should work.

**Comment by sega-yarkin** [comment]
@essen Thanks for your help! Now all tests passed, yay!))

**Comment by essen** [comment]
Merged, thanks!

**Pull request merged**
